[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "umlforge-backend"
version = "0.1.0"
description = "Herramienta CASE Colaborativa - Backend"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic[email]>=2.0.0",
    "jinja2>=3.1.0",
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.27.0",
    "python-multipart>=0.0.9",
    "pydantic-settings>=2.2.1",
    "lxml>=5.0.0",
    "sqlalchemy>=2.0.0",
    "alembic>=1.13.0",
    "psycopg2-binary>=2.9.9",
    "bcrypt>=4.0.0",
    "pyjwt>=2.8.0",
    "faster-whisper>=1.0.0",
    "google-generativeai>=0.4.0",
    "cohere>=7.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "black",
    "mypy",
    "httpx",
    "types-lxml>=2024.0.0"
]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["B008", "BLE001", "S110", "RUF012"]

[tool.mypy]
strict = true

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
