"""Add UniqueConstraint to DiagramPermission

Revision ID: d4a3c7c2bcb4
Revises: ff0d76120a11
Create Date: 2026-09-05 17:09:17.267982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a3c7c2bcb4'
down_revision: Union[str, Sequence[str], None] = 'ff0d76120a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_diagram_user_permission', 'diagram_permissions', ['diagram_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_diagram_user_permission', 'diagram_permissions', type_='unique')
    # ### end Alembic commands ###
