openapi: 3.0.1
info:
  title: Imported Model API
  version: 1.0.0
paths:
  "/api/admins":
    get:
      summary: Get all Admins
      tags:
        - Admin
      responses:
        "200":
          description: OK
  "/api/admins/{id}":
    get:
      summary: Get Admin by ID
      tags:
        - Admin
      responses:
        "200":
          description: OK
  "/api/admins":
    post:
      summary: Create Admin
      tags:
        - Admin
      responses:
        "200":
          description: OK
  "/api/admins/{id}":
    put:
      summary: Update Admin
      tags:
        - Admin
      responses:
        "200":
          description: OK
  "/api/admins/{id}":
    delete:
      summary: Delete Admin
      tags:
        - Admin
      responses:
        "200":
          description: OK
  "/api/categorias":
    get:
      summary: Get all Categorias
      tags:
        - Categoria
      responses:
        "200":
          description: OK
  "/api/categorias/{id}":
    get:
      summary: Get Categoria by ID
      tags:
        - Categoria
      responses:
        "200":
          description: OK
  "/api/categorias":
    post:
      summary: Create Categoria
      tags:
        - Categoria
      responses:
        "200":
          description: OK
  "/api/categorias/{id}":
    put:
      summary: Update Categoria
      tags:
        - Categoria
      responses:
        "200":
          description: OK
  "/api/categorias/{id}":
    delete:
      summary: Delete Categoria
      tags:
        - Categoria
      responses:
        "200":
          description: OK
  "/api/usuarios":
    get:
      summary: Get all Usuarios
      tags:
        - Usuario
      responses:
        "200":
          description: OK
  "/api/usuarios/{id}":
    get:
      summary: Get Usuario by ID
      tags:
        - Usuario
      responses:
        "200":
          description: OK
  "/api/usuarios":
    post:
      summary: Create Usuario
      tags:
        - Usuario
      responses:
        "200":
          description: OK
  "/api/usuarios/{id}":
    put:
      summary: Update Usuario
      tags:
        - Usuario
      responses:
        "200":
          description: OK
  "/api/usuarios/{id}":
    delete:
      summary: Delete Usuario
      tags:
        - Usuario
      responses:
        "200":
          description: OK
