openapi: 3.0.1
info:
  title: ConferenceBackend API
  version: 1.0.0
paths:
  "/api/conferences":
    get:
      summary: Get all Conferences
      tags:
        - Conference
      responses:
        "200":
          description: OK
  "/api/conferences/{id}":
    get:
      summary: Get Conference by ID
      tags:
        - Conference
      responses:
        "200":
          description: OK
  "/api/conferences":
    post:
      summary: Create Conference
      tags:
        - Conference
      responses:
        "200":
          description: OK
  "/api/conferences/{id}":
    put:
      summary: Update Conference
      tags:
        - Conference
      responses:
        "200":
          description: OK
  "/api/conferences/{id}":
    delete:
      summary: Delete Conference
      tags:
        - Conference
      responses:
        "200":
          description: OK
  "/api/topic_tracks":
    get:
      summary: Get all TopicTracks
      tags:
        - TopicTrack
      responses:
        "200":
          description: OK
  "/api/topic_tracks/{id}":
    get:
      summary: Get TopicTrack by ID
      tags:
        - TopicTrack
      responses:
        "200":
          description: OK
  "/api/topic_tracks":
    post:
      summary: Create TopicTrack
      tags:
        - TopicTrack
      responses:
        "200":
          description: OK
  "/api/topic_tracks/{id}":
    put:
      summary: Update TopicTrack
      tags:
        - TopicTrack
      responses:
        "200":
          description: OK
  "/api/topic_tracks/{id}":
    delete:
      summary: Delete TopicTrack
      tags:
        - TopicTrack
      responses:
        "200":
          description: OK
  "/api/attendees":
    get:
      summary: Get all Attendees
      tags:
        - Attendee
      responses:
        "200":
          description: OK
  "/api/attendees/{id}":
    get:
      summary: Get Attendee by ID
      tags:
        - Attendee
      responses:
        "200":
          description: OK
  "/api/attendees":
    post:
      summary: Create Attendee
      tags:
        - Attendee
      responses:
        "200":
          description: OK
  "/api/attendees/{id}":
    put:
      summary: Update Attendee
      tags:
        - Attendee
      responses:
        "200":
          description: OK
  "/api/attendees/{id}":
    delete:
      summary: Delete Attendee
      tags:
        - Attendee
      responses:
        "200":
          description: OK
  "/api/sessions":
    get:
      summary: Get all Sessions
      tags:
        - Session
      responses:
        "200":
          description: OK
  "/api/sessions/{id}":
    get:
      summary: Get Session by ID
      tags:
        - Session
      responses:
        "200":
          description: OK
  "/api/sessions":
    post:
      summary: Create Session
      tags:
        - Session
      responses:
        "200":
          description: OK
  "/api/sessions/{id}":
    put:
      summary: Update Session
      tags:
        - Session
      responses:
        "200":
          description: OK
  "/api/sessions/{id}":
    delete:
      summary: Delete Session
      tags:
        - Session
      responses:
        "200":
          description: OK
  "/api/keynote_speakers":
    get:
      summary: Get all KeynoteSpeakers
      tags:
        - KeynoteSpeaker
      responses:
        "200":
          description: OK
  "/api/keynote_speakers/{id}":
    get:
      summary: Get KeynoteSpeaker by ID
      tags:
        - KeynoteSpeaker
      responses:
        "200":
          description: OK
  "/api/keynote_speakers":
    post:
      summary: Create KeynoteSpeaker
      tags:
        - KeynoteSpeaker
      responses:
        "200":
          description: OK
  "/api/keynote_speakers/{id}":
    put:
      summary: Update KeynoteSpeaker
      tags:
        - KeynoteSpeaker
      responses:
        "200":
          description: OK
  "/api/keynote_speakers/{id}":
    delete:
      summary: Delete KeynoteSpeaker
      tags:
        - KeynoteSpeaker
      responses:
        "200":
          description: OK
